spring:
  application:
    name: configurator

  datasource:
    url: ${PG_URL}/configurator_db
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    username: ${MAIL_APP_NAME:me@gmail.com}
    password: ${MAIL_APP_PASSWORD}
    host: mail.liftmach.by
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 900MB

minio:
  url: http://localhost:9000
  accessKey: ${MINIO_ACCESS}
  secretKey: ${MINIO_SECRET}

keycloak:
  client:
    id: ${KEYCLOAK_CLIENT_NAME}
    secret: ${KEYCLOAK_CLIENT_SECRET}
  realm: configurator
  server-url: http://localhost:8080

springdoc:
  api-docs:
    path: /docs/v3/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html

server:
  port: 8090