spring:
  application:
    name: configurator

  datasource:
    url: ${PG_URL}/configurator_db
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 900MB

minio:
  bucket: texture
  publicUrl: http://localhost:9000
  url: http://localhost:9000
  accessKey: admin
  secretKey: password

scheduler:
  link-updating:
    cron: 0 0 0 * * 0

springdoc:
  api-docs:
    path: /docs/v3/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html

server:
  port: 8090