package com.dulfinne.configurator.entity.enums

enum class DocumentKey {
    ANNA_DATE,

    CABIN_SIZE,
    CABIN_TYPE,
    CABIN_OPENING_TYPE,
    DESIGN_PROJECT,

    WALL_BACK_MATERIAL,
    WALL_FRONT_MATERIAL,
    WALL_LEFT_MATERIAL,
    WALL_RIGHT_MATERIAL,

    HANDRAIL_EXISTENCE,
    HANDRAIL_MATERIAL,
    HANDRAIL_TYPE,
    HANDRAIL_LOCATION,

    MIRROR_EXISTENCE,
    MIRROR_TYPE,
    MIRROR_LOCATION,
    DOORS_MATERIAL,

    BUMPERS_MATERIAL,

    CEILING_LAMP,
    CEILING_MATERIAL,

    FLOOR_MATERIAL,

    CONTROL_PANEL_TYPE,
    CONTROL_PANEL_NAME,
    CONTROL_PANEL_SIDE,
    CONTROL_PANEL_LOCATION,
    CONTROL_PANEL_MATERIAL,

    CALL_POST_TYPE,
    CALL_POST_FRAME,
    CALL_POST_FRAME_MATERIAL,
    IND_BOARD_TYPE
}