package com.dulfinne.configurator.entity.enums

enum class DocumentKey {
    CABIN_SIZE,
    CABIN_TYPE,
    CABIN_OPENING_TYPE,

    WALL_BACK_MATERIAL,
    WALL_FRONT_MATERIAL,
    WALL_LEFT_MATERIAL,
    WALL_RIGHT_MATERIAL,

    HANDRAIL_EXISTENCE,
    HANDRAIL_MATERIAL,
    HANDRAIL_TYPE,
    HANDRAIL_LOCATION,

    MIRROR_EXISTENCE,
    MIRROR_TYPE,
    MIRROR_LOCATION,
    DOORS_MATERIAL,

    BUMPERS_RIGHT_MATERIAL,
    BUMPERS_LEFT_MATERIAL,
    BUMPERS_BACK_MATERIAL,

    CEILING_LAMP,
    CEILING_MATERIAL,
    CEILING_ORIENTATION,

    FLOOR_MATERIAL,

    CONTROL_PANEL_NAME,
    CONTROL_PANEL_SIDE,
    CONTROL_PANEL_LOCATION,
    CONTROL_PANEL_MATERIAL
}