name: 3d-configurator

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - configurator-service
      - frontend
      - frontend-admin

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    env_file:
      - ./env/keycloak.env
    ports:
      - "8080:8080"
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/

  postgres:
    image: postgres:17.0
    container_name: postgres
    expose:
      - "5432"
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database:/docker-entrypoint-initdb.d

  configurator-service:
    container_name: configurator-service
    image: dulfinne/configurator-service:latest
    expose:
      - "8090"
    env_file:
      - ./env/configurator-service.env
    depends_on:
      - postgres

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - ./env/minio.env
    command: server /data --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/data

  frontend:
    image: evgeniysavickiy/configurator-frontend
    container_name: configurator-frontend
    expose:
      - "80"

  frontend-admin:
    image: evgeniysavickiy/configurator-admin:latest
    container_name: configurator-admin
    expose:
      - "80"

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local