name: 3d-configurator

services:
  configurator_db:
    image: postgres:17.0
    container_name: configurator_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "configurator_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  configurator-service:
    container_name: configurator-service
    image: dulfinne/configurator-service:latest
    ports:
      - "8090:8090"
    environment:
      PG_URL: jdbc:postgresql://configurator_db:5432
      PG_USERNAME: "db"
      PG_PASSWORD: "123"
      MINIO_URL: http://minio:9000
    depends_on:
      - configurator_db

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/data

  frontend:
    image: evgeniysavickiy/configurator-frontend
    container_name: configurator-frontend
    ports:
      - "3000:80"

  frontend-admin:
    image: evgeniysavickiy/configurator-admin:latest
    container_name: configurator-admin
    ports:
      - "8088:80"

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local