name: 3d-configurator

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: db
      KC_DB_PASSWORD: 123
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/

  postgres:
    image: postgres:17.0
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database:/docker-entrypoint-initdb.d

  configurator-service:
    container_name: configurator-service
    image: dulfinne/configurator-service:latest
    ports:
      - "8090:8090"
    environment:
      PG_URL: jdbc:postgresql://postgres:5432
      PG_USERNAME: "db"
      PG_PASSWORD: "123"
      MINIO_URL: http://minio:9000
      KEYCLOAK_SERVER_URL: http://keycloak:8080
    depends_on:
      - postgres

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/data

  frontend:
    image: evgeniysavickiy/configurator-frontend
    container_name: configurator-frontend
    ports:
      - "3000:80"

  frontend-admin:
    image: evgeniysavickiy/configurator-admin:latest
    container_name: configurator-admin
    ports:
      - "8088:80"

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local